### ISSUE TITLE
PPO OOM 8*A100 40G

### ISSUE THREAD

**Issue by tbsxxxH** [OpenRLHF/OpenRLHF#398]
[rank7]: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 112.00 MiB. GPU 7 has a total capacity of 39.39 GiB of which 14.00 MiB is free. Process 1117993 has 39.36 GiB memory in use. Of the allocated memory 38.34 GiB is allocated by PyTorch, and 385.64 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[2024-08-02 01:24:59,694] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 33131

**Comment by tbsxxxH** [comment]
train_ppo_llama.sh

set -x 

read -r -d '' training_commands <<EOF
openrlhf.cli.train_ppo \
   --pretrain /home/eva.liu/OpenRLHF/examples/scripts/lora_model \
   --reward_pretrain /home/eva.liu/OpenRLHF/examples/scripts/checkpoint/llama3-8b-rm \
   --save_path ./checkpoint/llama-3-8b-rlhf \
   --save_steps -1 \
   --logging_steps 1 \
   --eval_steps -1 \
   --micro_train_batch_size 2 \
   --train_batch_size 64 \
   --micro_rollout_batch_size 4 \
   --rollout_batch_size 512 \
   --max_epochs 1 \
   --prompt_max_len 1024 \
   --generate_max_len 1024 \
   --zero_stage 2 \
   --bf16 \
   --actor_learning_rate 5e-7 \
   --critic_learning_rate 9e-6 \
   --init_kl_coef 0.01 \
   --prompt_data /home/eva.liu/OpenRLHF/datasets/datasets_rm \
   --input_key prompt \
   --max_samples 100000 \
   --normalize_reward \
   --adam_offload \
   --flash_attn \
   --load_checkpoint \
   --gradient_checkpointing
EOF
    # --wandb [WANDB_TOKENS] or True (use wandb login command)
    # --remote_rm_url http://localhost:5000/get_reward

if [[ ${1} != "slurm" ]]; then
    deepspeed --module $training_commands
fi

**Comment by tbsxxxH** [comment]
> [rank7]： torch.cuda.OutOfMemoryError： CUDA 内存不足。尝试分配 112.00 MiB。GPU 7 的总容量为 39.39 GiB，其中 14.00 MiB 是免费的。进程 1117993 正在使用 39.36 GiB 内存。在分配的内存中，38.34 GiB 由 PyTorch 分配，385.64 MiB 由 PyTorch 保留但未分配。如果预留但未分配的内存很大，请尝试设置 PYTORCH_CUDA_ALLOC_CONF=expandable_segments：True 以避免碎片化。请参阅内存管理 （https://pytorch.org/docs/stable/notes/cuda.html#environment-variables） [2024-08-02 01：24：59,694] [INFO] [launch.py：319：sigkill_handler] 杀死子进程 33131 的文档

I used 8*RTX3090 before and the error "tried to allocate 112.00 MiB" appeared. After changing to A100, the same error still occurred.

**Comment by hijkzzz** [comment]
请使用 ray ppo，40GB 内存不用 ray  太小了

**Comment by tbsxxxH** [comment]
> 请使用 ray ppo，40GB 内存不用 ray 太小了。并且不要合并模型节点 --coxxxx

合并模型节点指的是pretrain这里面，就用sft产生的吗？

**Comment by hijkzzz** [comment]
> 

ray ppo 里面的用法

**Comment by tbsxxxH** [comment]
> > 
> 
> ray ppo 里面的用法，参考 https://openrlhf.readthedocs.io/en/latest/usage.html#ppo-with-ray-vllm

我安装了datasets，之前由pip install openrlhf，启动ray之后出现了这样的问题：
---------------------------------------
Job 'raysubmit_Tvn5UksTQpdbsCUM' failed
---------------------------------------

Status message: Job entrypoint command failed with exit code 1, last available logs (truncated to 20,000 chars):
    from openrlhf.models import DPOLoss
  File "/usr/local/lib/python3.10/dist-packages/openrlhf/models/__init__.py", line 3, in <module>
    from .model import get_llm_for_sequence_regression
  File "/usr/local/lib/python3.10/dist-packages/openrlhf/models/model.py", line 14, in <module>
    from openrlhf.utils.logging_utils import init_logger
  File "/usr/local/lib/python3.10/dist-packages/openrlhf/utils/__init__.py", line 3, in <module>
    from .utils import blending_datasets, get_strategy, get_tokenizer
  File "/usr/local/lib/python3.10/dist-packages/openrlhf/utils/utils.py", line 4, in <module>
    from datasets import Dataset, interleave_datasets, load_dataset
ImportError: cannot import name 'Dataset' from 'datasets' (/tmp/ray/session_2024-08-02_01-48-35_552077_40933/runtime_resources/working_dir_files/_ray_pkg_fb4da693921c2816/datasets/__init__.py)

**Comment by hijkzzz** [comment]
启动时候加一行 --runtime-env-json='{"setup_commands": ["pip install openrlhf[vllm]"]}' 试试

**Comment by tbsxxxH** [comment]
> 启动时候加一行 --runtime-env-json='{"setup_commands": ["pip install openrlhf[vllm]"]}' 试试

刚才的问题解决啦，谢谢了，可是随之而来的就出现了另外的错误，我并没有修改过有关API的参数，不知道这个错误，来源于哪里？
Job 'raysubmit_uPc1cjBpK51Jzbj5' failed

Status message: Job entrypoint command failed with exit code 1, last available logs (truncated to 20,000 chars):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_login.py", line 84, in login
    configured = _login(
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_login.py", line 340, in _login
    wlogin.configure_api_key(key)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_login.py", line 221, in configure_api_key
    apikey.write_key(self._settings, key)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/apikey.py", line 252, in write_key
    raise ValueError(
ValueError: API key must be 40 characters long, yours was 13
(ActorModelRayActor pid=49186) wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin

**Comment by hijkzzz** [comment]
ValueError: API key must be 40 characters long, yours was 13

**Comment by tbsxxxH** [comment]
> ValueError: API key must be 40 characters long, yours was 13

但是我并没有修改和设置过API key，我不知道为什么会出现这样的问题

**Comment by tbsxxxH** [comment]
> > ValueError: API key must be 40 characters long, yours was 13
> 
> 但是我并没有修改和设置过API key，我不知道为什么会出现这样的问题

解决了，在wanbd官网领取了API

**Comment by lc222** [comment]
> > > 
> > 
> > 
> > ray ppo 里面的用法，参考 https://openrlhf.readthedocs.io/en/latest/usage.html#ppo-with-ray-vllm
> 
> 我安装了datasets，之前由pip install openrlhf，启动ray之后出现了这样的问题： Job 'raysubmit_Tvn5UksTQpdbsCUM' failed Status message: Job entrypoint command failed with exit code 1, last available logs (truncated to 20,000 chars): from openrlhf.models import DPOLoss File "/usr/local/lib/python3.10/dist-packages/openrlhf/models/**init**.py", line 3, in from .model import get_llm_for_sequence_regression File "/usr/local/lib/python3.10/dist-packages/openrlhf/models/model.py", line 14, in from openrlhf.utils.logging_utils import init_logger File "/usr/local/lib/python3.10/dist-packages/openrlhf/utils/**init**.py", line 3, in from .utils import blending_datasets, get_strategy, get_tokenizer File "/usr/local/lib/python3.10/dist-packages/openrlhf/utils/utils.py", line 4, in from datasets import Dataset, interleave_datasets, load_dataset ImportError: cannot import name 'Dataset' from 'datasets' (/tmp/ray/session_2024-08-02_01-48-35_552077_40933/runtime_resources/working_dir_files/_ray_pkg_fb4da693921c2816/datasets/**init**.py)

嗨，想问下这个问题是如何解决的，我也遇到了同样的问题，我已经安装了openrlhf和datasets包
