### ISSUE TITLE
Context Parallel Failded for Modified SFT Trainer

### ISSUE THREAD

**Issue by ZetangForward** [OpenRLHF/OpenRLHF#468]
Update 2024/10/21

Hi, after debugging, I find `rank: 7, local_label shape: torch.Size([1, 3086]), locak_label max: 128009, locak_label min: -100, logits_shape: torch.Size([1, 3086, 128256])`  In SFT training, the Padding token is set to -100 by default, thereby leading to the error.

Now, I have modified the code like this, and the code can now run normally:

```
class GPTLMLoss(nn.Module):
    """
    GPT Language Model Loss
    """

    def __init__(self):
        super().__init__()
        self.IGNORE_INDEX = -100
        self.loss = nn.CrossEntropyLoss(ignore_index=self.IGNORE_INDEX)

    def forward(self, logits: torch.Tensor, labels: torch.Tensor) -> torch.Tensor:
        shift_logits = logits[..., :-1, :].contiguous()
        shift_labels = labels[..., 1:].contiguous()
        # Flatten the tokens
        return self.loss(shift_logits.view(-1, shift_logits.size(-1)), shift_labels.view(-1))

...

for prompts_id_lens, inputs, attention_masks, infos in self.train_dataloader:
      if self.packing_samples:
          inputs = inputs.to(torch.cuda.current_device())
          attention_mask = attention_masks.to(torch.cuda.current_device())
          
          logits = self.model(
              inputs, attention_mask=attention_mask, 
              ring_attn_group=self.strategy.ring_attn_group,
              packed_seq_lens=prompts_id_lens, 
              return_output=True,
          )["logits"]
          
          ## gather all the logits
          all_logits = all_gather(logits, self.strategy.ring_attn_group).reshape((1, -1, logits.size(-1)))
         
          ## compute the ce loss
          labels = torch.where(attention_mask.bool(), inputs, self.loss_fn.IGNORE_INDEX)
          gpt_loss = self.loss_fn(all_logits, labels)  # GPTLMLoss

```

I wonder if this code is right？  
If possible, I hope I can contribute to the Ring Attention feature in SFT Trainer

---
2024/10/20

Hi, I modified the code in [SFT Trainer](https://github.com/OpenRLHF/OpenRLHF/blob/main/openrlhf/trainer/sft_trainer.py)
Specifically, I change the code for the `def fit()` function:

```
def fit(self, args, consumed_samples=0, num_update_steps_per_epoch=None):
        # get eval and save steps
        if args.eval_steps == -1:
            args.eval_steps = 10000000  # Evaluate once per epoch
        if args.save_steps == -1:
            args.save_steps = float("inf")  # do not save ckpt

        # Restore step and start_epoch
        step = consumed_samples // args.train_batch_size * self.strategy.accumulated_gradient + 1
        start_epoch = consumed_samples // args.train_batch_size // num_update_steps_per_epoch
        consumed_samples = consumed_samples % (num_update_steps_per_epoch * args.train_batch_size)

        epoch_bar = tqdm(
            range(start_epoch, self.epochs),
            desc="Train epoch",
            disable=not self.strategy.is_rank_0(),
        )
        for epoch in range(start_epoch, self.epochs):
            if isinstance(self.train_dataloader.sampler, DistributedSampler):
                self.train_dataloader.sampler.set_epoch(
                    epoch, consumed_samples=0 if epoch > start_epoch else consumed_samples
                )

            step_bar = tqdm(
                range(self.train_dataloader.__len__()),
                desc="Train step of epoch %d" % epoch,
                disable=not self.strategy.is_rank_0(),
            )

            # train
            self.model.train()
            loss_mean = 0
            for prompts_id_lens, inputs, attention_masks, infos in self.train_dataloader:
                if self.packing_samples:
                    inputs = inputs.to(torch.cuda.current_device())
                    attention_mask = attention_masks.to(torch.cuda.current_device())
                    
                    logits = self.model(
                        inputs, attention_mask=attention_mask, 
                        ring_attn_group=self.strategy.ring_attn_group,
                        packed_seq_lens=prompts_id_lens, 
                        return_output=True,
                    )["logits"]
                    
                    rank = self.strategy.ring_attn_rank
                    
                    labels = torch.where(
                        attention_mask.bool(),
                        inputs,
                        self.loss_fn.IGNORE_INDEX,
                    )

                    total_seq_len = labels.numel()
                    local_seq_len = total_seq_len // self.strategy.ring_attn_size
                    local_slice = slice(rank * local_seq_len + 1, (rank + 1) * local_seq_len + 1)
                    local_label = labels[:, local_slice]
                    if rank == self.strategy.ring_attn_size - 1:
                    # add a dummy label to the last logit
                        local_label = F.pad(local_label, (0, 1), value=0)

                    print(f"rank: {rank}, local_label shape: {local_label.shape}, locak_label max: {local_label.max()}, logits_shape: {logits.shape}\n")
                    local_per_token_logps = torch.gather(
                        logits.log_softmax(-1), dim=2, index=local_label.unsqueeze(2)
                    ).squeeze(2)

                    per_token_logps = all_gather(local_per_token_logps, self.strategy.ring_attn_group).reshape((1, -1))

                    loss_masks = attention_mask.clone().bool()

                    index = 0
                    for i, seq_len in enumerate(prompts_id_lens):
                        loss_masks[0, index : index + prompts_id_lens[i]] = False
                        index = index + seq_len

                    loss_masks = loss_masks[:, 1:]

                    logprobs_sums = []
                    logprobs_means = []
                    index = 0
                    for i, seq_len in enumerate(prompts_id_lens):
                        seq = per_token_logps[0, index : index + seq_len - 1]
                        mask = loss_masks[0, index : index + seq_len - 1]
                        logprobs_sums.append((seq * mask).sum())
                        logprobs_means.append((seq * mask).sum() / mask.sum())
                        index = index + seq_len
                    gpt_loss = torch.stack(logprobs_means).mean()
 ```

However, there is an error when the code runs to this line: 
```
local_per_token_logps = torch.gather(logits.log_softmax(-1), dim=2, index=local_label.unsqueeze(2)).squeeze(2)
```

Error is:
```
./aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [6,0,0], thread: [10,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [6,0,0], thread: [11,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [6,0,0], thread: [12,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
[rank7]: Traceback (most recent call last):
[rank7]:   File "/data/zecheng/MyRLHF/openrlhf/cli/train_sft_dev.py", line 249, in <module>
[rank7]:     train(args)
[rank7]:   File "/data/zecheng/MyRLHF/openrlhf/cli/train_sft_dev.py", line 142, in train
[rank7]:     trainer.fit(args, consumed_samples, num_update_steps_per_epoch)
[rank7]:   File "/data/zecheng/MyRLHF/openrlhf/trainer/sft_trainer.py", line 160, in fit
[rank7]:     local_per_token_logps = torch.gather(
[rank7]: RuntimeError: CUDA error: device-side assert triggered
[rank7]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

I print the tensor shape and the value in it and it seems right:
```
ank: 0, local_label shape: torch.Size([1, 3086]), locak_label max: 128007, logits_shape: torch.Size([1, 3086, 128256])

rank: 1, local_label shape: torch.Size([1, 3086]), locak_label max: 125824, logits_shape: torch.Size([1, 3086, 128256])

rank: 4, local_label shape: torch.Size([1, 3086]), locak_label max: 98266, logits_shape: torch.Size([1, 3086, 128256])

rank: 5, local_label shape: torch.Size([1, 3086]), locak_label max: 98662, logits_shape: torch.Size([1, 3086, 128256])

rank: 2, local_label shape: torch.Size([1, 3086]), locak_label max: 96798, logits_shape: torch.Size([1, 3086, 128256])

rank: 6, local_label shape: torch.Size([1, 3086]), locak_label max: 98662, logits_shape: torch.Size([1, 3086, 128256])

rank: 3, local_label shape: torch.Size([1, 3086]), locak_label max: 109524, logits_shape: torch.Size([1, 3086, 128256])

rank: 7, local_label shape: torch.Size([1, 3086]), locak_label max: 128009, logits_shape: torch.Size([1, 3086, 128256])
```

In my training script, I set --ring_attn_size 8, and whatever value I change, I still face this issue.

Any suggestion to solve this issue? Thanks.

@zhuzilin @tsaoyu

**Comment by ZetangForward** [comment]
I find `rank: 7, local_label shape: torch.Size([1, 3086]), locak_label max: 128009, locak_label min: -100, logits_shape: torch.Size([1, 3086, 128256])`

In SFT training, the Padding token is set to -100 by default. How can I avoid first getting local_per_token_logps and then calculating SFT loss? Can I calculate the loss for each local context and then add them together?

**Comment by hijkzzz** [comment]
@zhuzilin

**Comment by zhuzilin** [comment]
@ZetangForward
> If possible, I hope I can contribute to the Ring Attention feature in SFT Trainer
That will be great!

In fact, it will be better for us to communicate if you could send a PR for this feature, because we could check the code diff much easier.

btw, I believe #444 could be served as an example to add ring attention to sft trainer. And you probably need to make some changes in the `SFTDataset`, similar to `RewardDataset`.

**Comment by ZetangForward** [comment]
> @ZetangForward
> 
> > If possible, I hope I can contribute to the Ring Attention feature in SFT Trainer
> 
> That will be great!
> 
> In fact, it will be better for us to communicate if you could send a PR for this feature, because we could check the code diff much easier.
> 
> btw, I believe #444 could be served as an example to add ring attention to sft trainer. And you probably need to make some changes in the `SFTDataset`, similar to `RewardDataset`.

Hi, I have already changed the `SFTDataset,` and Can I add a WeChat with you for convenient communication?

**Comment by zhuzilin** [comment]
> if it is possible to calculate the loss separately on each chunk and the backward loss separately to decrease the GPU's memory consumption.

hmm.. As long as you figure out how to make last token of each chunk have the correct label (except the last token of the last chunk, which have no corresponding token), you can do that. 
I sugguest doing an all reduce after calculating the loss so that the wandb log will be the same (may be not a simple allreduce, but some weighted mean...)

**Comment by ZetangForward** [comment]
This issue has been solved in https://github.com/OpenRLHF/OpenRLHF/pull/477#event-14901189417
