### ISSUE TITLE
多机多卡下开启vllm engine会卡住

### ISSUE THREAD

**Issue by CPFLAME** [OpenRLHF/OpenRLHF#492]
## 环境
环境采用的是readme提到的dockerfile，和pip install 的安装方式。显卡是**2机16卡**的A800， 目前的情况是在2机16卡下开了vllm engine以后就会直接卡住。
几个比较重要的包：
torch: 2.3.0+cu121
ray: 2.12.0
vllm: 0.4.2

## 目前表现
1. 目前不用ray的脚本，采用torchrun的方式, 2机16卡下面可以跑通.
2. 用ray的脚本，比如`examples/scripts/train_ppo_llama_ray.sh`，在2机16卡的情况下，把`vllm_num_engines`设置为0，可以跑通
3. 用ray的脚本，比如`examples/scripts/train_ppo_llama_ray.sh`， 在**单机8卡**下面可以跑通。
-  只在单机上运行ray start --head --node-ip-address 0.0.0.0 --num-gpus 8
-  修改以下配置
```
   --ref_num_nodes 1 \
   --ref_num_gpus_per_node 2 \
   --reward_num_nodes 1 \
   --reward_num_gpus_per_node 2 \
   --critic_num_nodes 1 \
   --critic_num_gpus_per_node 2 \
   --actor_num_nodes 1 \
   --actor_num_gpus_per_node 2 \
   --vllm_num_engines 4 \
   --vllm_tensor_parallel_size 1 \
```
4. 在2机16卡上，设置了`vllm_num_engine`以后，会直接卡住

-   在master节点上运行`ray start --head --node-ip-address 0.0.0.0 --num-gpus 8`, 在worker节点上运行`ray start --address ${MASTER_ADDR}:6379  --num-gpus 8`
-   修改配置为
```
ray job submit --address="http://127.0.0.1:8265" \
   --runtime-env-json='{"working_dir": "/path/to/OpenRLHF"}' \
   -- python3 -m openrlhf.cli.train_ppo_ray \
   --ref_num_nodes 1 \
   --ref_num_gpus_per_node 4 \
   --reward_num_nodes 1 \
   --reward_num_gpus_per_node 4 \
   --critic_num_nodes 1 \
   --critic_num_gpus_per_node 4 \
   --actor_num_nodes 1 \
   --actor_num_gpus_per_node 4 \
   --vllm_num_engines 8 \
   --vllm_tensor_parallel_size 1 \
   ...
```
3) 发现代码会直接卡住。

## 尝试定位bug
1. 首先怀疑是vllm的问题
于是在2机16卡上跑了一下`openrlhf/trainer/ray/vllm_engine.py`,  设置了TP为16， 发现是可以跑通的
```
if __name__ == "__main__":
    llm = LLMRayActor.remote("/path/to/Meta-Llama-3-8B-hf/", tensor_parallel_size=16)
    output = ray.get(llm.generate.remote("San Franciso is a"))
    print(f"output: {output}")
```

2. 尝试定位程序是卡在了哪里，在自己加入了log信息以后，发现程序卡在了[ppo_actor.py](https://github.com/OpenRLHF/OpenRLHF/blob/685a9605580d1149b4763aefe5b26b7c84ced4df/openrlhf/trainer/ray/ppo_actor.py#L94-L113)下面，
```python
            refs = [
                engine.init_process_group.remote(
                    master_address,
                    master_port,
                    i * vllm_tensor_parallel_size + 1,
                    world_size,
                    "openrlhf",
                    backend=backend,
                )
                for i, engine in enumerate(self.vllm_engines)
            ]
            ...
            ray.get(refs)
```
这里的ray在获取返回结果的时候就直接卡住了， 请问作者有什么比较好的思路吗？ 或者需要我提供什么额外的信息来帮忙定位bug吗？

**Comment by hijkzzz** [comment]
actor_num_gpus_per_node * actor_num_nodes  要 >= vllm_num_engines

**Comment by CPFLAME** [comment]
看上去并不是因为这个原因，我用下面这个配置跑了一下， 在2机16卡上，仍然会出现卡住的现象：
```
ray job submit --address="http://127.0.0.1:8265" \
   --runtime-env-json='{"working_dir": "/path/to/OpenRLHF"}' \
   -- python3 -m openrlhf.cli.train_ppo_ray \
   --ref_num_nodes 1 \
   --ref_num_gpus_per_node 2 \
   --reward_num_nodes 1 \
   --reward_num_gpus_per_node 2 \
   --critic_num_nodes 1 \
   --critic_num_gpus_per_node 4 \
   --actor_num_nodes 1 \
   --actor_num_gpus_per_node 4 \
   --vllm_num_engines 2 \
   --vllm_tensor_parallel_size 2 \
   --pretrain /path/to/Llama-3-8b-rm-mixture \
   --reward_pretrain /path/to/Llama-3-8b-rm-mixture \
   --save_path /path/to/models/llama3-8b-rlhf \
   --micro_train_batch_size 1 \
   --train_batch_size 16 \
   --micro_rollout_batch_size 2 \
   --rollout_batch_size 32 \
   --max_samples 100000 \
   --max_epochs 1 \
   --prompt_max_len 1024 \
   --generate_max_len 1024 \
   --zero_stage 3 \
   --bf16 \
   --actor_learning_rate 5e-7 \
   --critic_learning_rate 9e-6 \
   --init_kl_coef 0.01 \
   --prompt_data /path/to/data/math_train_processed.jsonl \
   --input_key chat_messages \
   --apply_chat_template \
   --normalize_reward \
   --adam_offload \
   --flash_attn \
   --gradient_checkpointing \
```

**Comment by platoonpluto** [comment]
is this solved????

**Comment by platoonpluto** [comment]
> 看上去并不是因为这个原因，我用下面这个配置跑了一下， 在2机16卡上，仍然会出现卡住的现象：
> 
> ```
> ray job submit --address="http://127.0.0.1:8265" \
>    --runtime-env-json='{"working_dir": "/path/to/OpenRLHF"}' \
>    -- python3 -m openrlhf.cli.train_ppo_ray \
>    --ref_num_nodes 1 \
>    --ref_num_gpus_per_node 2 \
>    --reward_num_nodes 1 \
>    --reward_num_gpus_per_node 2 \
>    --critic_num_nodes 1 \
>    --critic_num_gpus_per_node 4 \
>    --actor_num_nodes 1 \
>    --actor_num_gpus_per_node 4 \
>    --vllm_num_engines 2 \
>    --vllm_tensor_parallel_size 2 \
>    --pretrain /path/to/Llama-3-8b-rm-mixture \
>    --reward_pretrain /path/to/Llama-3-8b-rm-mixture \
>    --save_path /path/to/models/llama3-8b-rlhf \
>    --micro_train_batch_size 1 \
>    --train_batch_size 16 \
>    --micro_rollout_batch_size 2 \
>    --rollout_batch_size 32 \
>    --max_samples 100000 \
>    --max_epochs 1 \
>    --prompt_max_len 1024 \
>    --generate_max_len 1024 \
>    --zero_stage 3 \
>    --bf16 \
>    --actor_learning_rate 5e-7 \
>    --critic_learning_rate 9e-6 \
>    --init_kl_coef 0.01 \
>    --prompt_data /path/to/data/math_train_processed.jsonl \
>    --input_key chat_messages \
>    --apply_chat_template \
>    --normalize_reward \
>    --adam_offload \
>    --flash_attn \
>    --gradient_checkpointing \
> ```

@CPFLAME 后来解决掉了吗？我也遇到相同的问题了。

**Comment by lc222** [comment]
> @hijkzzz is this solved????

嗨，解决了吗?我也遇到了这个问题@hijkzzz

**Comment by LUMO666** [comment]
我也遇到了这个问题。。。。。。两机就可以复现

**Comment by CPFLAME** [comment]
@platoonpluto @lc222 @LUMO666 
这个问题我解决了，讲一下我的解决经历，在定位到是init_process_group这里卡住了以后，我进行了如下尝试：

### 代码改动
1.  先把openrlhf/utils/distributed_util.py下的init_process_group里面的initial_method改成file共享文件的的方式，不使用tcp进行通信。 这个只需要在启动的时候设置一个所有node都可以访问到的空文件地址（权限设置为777）就可以了运行了`export PYTORCH_ENV_FILE_PATH=/path/to/file`
```python
def init_process_group(
    backend: Union[str, Backend] = None,
    init_method: Optional[str] = None,
    timeout: Optional[timedelta] = None,
    world_size: int = -1,
    rank: int = -1,
    store: Optional[Store] = None,
    group_name: str = None,
    pg_options: Optional[Any] = None,
):
    assert (store is None) or (init_method is None), "Cannot specify both init_method and store."

    if store is not None:
        assert world_size > 0, "world_size must be positive if using store"
        assert rank >= 0, "rank must be non-negative if using store"
    elif init_method is None:
        init_method = "env://"

    if os.getenv("PYTORCH_ENV_FILE_PATH") is not None:
        init_method = "file://" + os.getenv("PYTORCH_ENV_FILE_PATH")
    else:
        # raise RuntimeError("PYTORCH_ENV_FILE_PATH is not set")
        pass
```
但是有一些奇怪的是，通过这种方法运行，会时灵时不灵，偶尔成功，偶尔hang住，而且经常需要新建立一个地址才可以。
但是一旦从3机scale到6机，会一直hang住。

2.  虽然第一种方法可以跑，但是机器一旦多起来以后，就会直接hang住，现在需求又需要用多机跑。没办法，开始找根本原因。这个时候我注意到了一行代码：
https://github.com/OpenRLHF/OpenRLHF/blob/f5c137fe2b0bd2f2369140d8e73e7cec07d7335c/openrlhf/trainer/ray/ppo_actor.py#L73-L76

把它改成了
```python
            master_address = os.environ.get("MASTER_ADDR", ray._private.services.get_node_ip_address())
            # master_address = "dlc1gbif47ch01av-master-0"
            with socket.socket() as sock:
                sock.bind(("", 0))
                master_port = int(os.environ.get("MASTER_PORT", sock.getsockname()[1]))
```
把通信方式的init_method换成原始的tcp(也就是不设置环境变量`PYTORCH_ENV_FILE_PATH`)，然后解决了问题。

### 原因
首先我们明白一个原理：
1. 在pytorch里面我们多机去跑的时候要设置init_process_group，然后需要设置统一的master_addr和master_port才可以进行通信。
2. 如果不同机器上的master_addr和master_port设置的不一致，然后同一个group里面达不到的world_size的数量，就会一直等待。

OPENRLHF在init_process_group的时候，master_addr和master_port采用了一个ray的函数自己去找的，在阿里云的环境下，这两个变量在不同的机器上用ray函数自己去找，可能会产生不一致的问题，那么一旦不一致，那么一个group里面就达不到的world_size的数量，就会hang住。

所以运用阿里云启动torch任务的特性，每个机器节点里面都有master_addr和master_port，我们直接把环境变量里面的master_addr和master_port赋值进去就可以了，这可以保证每台机器上都是同一个ip.

### 思考
1. 为什么换成file共享文件的方式可以跑起来？

因为通过用file共享文件的通信方式跳过了tcp的master_addr和master_port设置，这个不一致的问题被避免了

2. 为什么file共享文件的方式scale到6机上就跑不起来了？

个人猜测（没有证实）：目前观察到一个现象是，一旦多个程序共同使用一个file文件地址，可能会发生抢占之类的情况，导致hang住。这也是为什么我们前期跑的时候偶尔成功偶尔失败。一个地址用的程序越多，越容易卡住，scale到6卡的时候卡住的几率非常之高了。一直没有跑成功过

**Comment by hijkzzz** [comment]
这里还是有一个问题是 master addr 对于 actor group / critic group 可能不是同一个。因为他们可能分散到不同的节点上了，所以还是有点问题。
