### ISSUE TITLE
[PPO Potential Issue] Hanging at torch.distributed.barrier() When Remote RM and Actor Are on the Same Host

### ISSUE THREAD

**Issue by KKKe2922** [OpenRLHF/OpenRLHF#689]
First, thank you for your excellent work on this open-source project. It has been invaluable for my research.

I’ve encountered a potential issue in my PPO setup when both the remote model (RM) and actor are running on the same host, with the actor not utilizing all available GPUs. Specifically, the program hangs at `torch.distributed.barrier()` during data synchronization.

Setup:
	•	3 GPUs in total
	•	1 GPU assigned to the remote model (due to a different architecture for the reward model)
	•	2 GPUs assigned to the actor with the setting:

export CUDA_VISIBLE_DEVICES=0,1

Issue:

In my experiments, after `self.generate_samples` in OpenRLHF/openrlhf/trainer/ppo_utils/experience_maker.py, the program hangs at `torch.distributed.barrier()` when only 2 GPUs are used. The process works fine with 3 GPUs.

Is this behavior expected, or could there be an issue with the configuration? Any insights would be greatly appreciated.

**Comment by ColaZhang22** [comment]
Same issues.
When I try to train a PPO algorithm in 8 GPUs, it is hanging at **torch.distributed.barrier()** in **experience_maker.py**.
Once a process entered **torch.distributed.barrier()**, all other processes are blocked.

Envrionment is **python 3.10**+**torch 2.4.1+cu118** + **deepspeed  0.15.0**

Any advices would be greatly appreciated.

**Comment by wangzhen0518** [comment]
Same here.
Train ppo using `examples/scripts/train_ppo_llama.sh` with 8 A100. The training hung after one process finished `generate_samples` and entered `torch.distributed.barrier()`. It seems that the process which finished generating is waiting for other processes to enter the barrier, while the other processes are waiting for that process to release the GPU.

**Comment by wangzhen0518** [comment]
I changed `zero_stage` from 3 to 2, then the problem disappeared. However, I have no idea about the reason. 😭

**Comment by wangkevin02** [comment]
> I changed `zero_stage` from 3 to 2, then the problem disappeared. However, I have no idea how it works. 😭

I think it may be that the author <u>customized some configurations of zero3</u>, but even zero2 **only crossed the barrier of making experience**, but the barrier **still stuck when saving ckpt**.
