### ISSUE TITLE
NCCL error when colocate_actor_ref using newest vllm

### ISSUE THREAD

**Issue by eyuansu62** [OpenRLHF/OpenRLHF#744]
My command is:
```
ray job submit --address="http://127.0.0.1:8265" \
   --runtime-env-json '{"env_vars": {"HF_ENDPOINT": "https://hf-mirror.com", "TOKENIZERS_PARALLELISM": "false", "NCCL_DEBUG": "INFO"}}' \
   -- python3 -m openrlhf.cli.train_ppo_ray \
   --ref_num_nodes 1 \
   --ref_num_gpus_per_node 2 \
   --remote_rm_url http://localhost:5000/get_reward \
   --actor_num_nodes 1 \
   --actor_num_gpus_per_node 2 \
   --vllm_num_engines 2 \
   --vllm_tensor_parallel_size 1 \
   --colocate_actor_ref \
   --pretrain /share/project/huggingface/models/OLMo-7B-0724-Instruct-hf \
   --save_path /openrlhf/examples/test_scripts/checkpoint/llama3-8b-rlhf \
   --micro_train_batch_size 16 \
   --train_batch_size 128 \
   --micro_rollout_batch_size 32 \
   --rollout_batch_size 1024 \
   --n_samples_per_prompt 1 \
   --max_epochs 1 \
   --prompt_max_len 1024 \
   --max_samples 100000 \
   --generate_max_len 1024 \
   --advantage_estimator reinforce \
   --zero_stage 3 \
   --bf16 \
   --actor_learning_rate 5e-7 \
   --init_kl_coef 0.01 \
   --prompt_data OpenRLHF/prompt-collection-v0.1 \
   --input_key context_messages \
   --apply_chat_template \
   --normalize_reward \
   --adam_offload \
   --gradient_checkpointing \
   --packing_samples \
   --save_steps -1 \
   --ckpt_path /openrlhf/examples/test_scripts/ckpt/llama3-8b-rlhf
```

```
Traceback (most recent call last):
  File "/root/miniconda3/envs/zero/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/zero/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/root/OpenRLHF/openrlhf/cli/train_ppo_ray.py", line 426, in <module>
    train(args)
  File "/home/root/OpenRLHF/openrlhf/cli/train_ppo_ray.py", line 163, in train
    ray.get(refs)
  File "/root/miniconda3/envs/zero/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/zero/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/zero/lib/python3.10/site-packages/ray/_private/worker.py", line 2623, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/root/miniconda3/envs/zero/lib/python3.10/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(DistBackendError): [36mray::ActorModelRayActor.init_model_from_pretrained()[39m (pid=810343, ip=172.24.40.143, actor_id=20d73dca27cfcc3db494094907000000, repr=<openrlhf.trainer.ray.ppo_actor.ActorModelRayActor object at 0x7f4f0149c550>)
  File "/home/root/OpenRLHF/openrlhf/trainer/ray/ppo_actor.py", line 346, in init_model_from_pretrained
    actor = Actor(
  File "/home/root/OpenRLHF/openrlhf/models/actor.py", line 73, in __init__
    self.model = AutoModelForCausalLM.from_pretrained(
  File "/root/miniconda3/envs/zero/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
  File "/root/miniconda3/envs/zero/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4111, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/root/miniconda3/envs/zero/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 511, in wrapper
    f(module, *args, **kwargs)
  File "/root/miniconda3/envs/zero/lib/python3.10/site-packages/transformers/models/olmo/modeling_olmo.py", line 727, in __init__
    self.model = OlmoModel(config)
  File "/root/miniconda3/envs/zero/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 511, in wrapper
    f(module, *args, **kwargs)
  File "/root/miniconda3/envs/zero/lib/python3.10/site-packages/transformers/models/olmo/modeling_olmo.py", line 472, in __init__
    self.embed_tokens = nn.Embedding(config.vocab_size, config.hidden_size, self.padding_idx)
  File "/root/miniconda3/envs/zero/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 521, in wrapper
    self._post_init_method(module)
  File "/root/miniconda3/envs/zero/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1100, in _post_init_method
    self._zero_init_param(param)
  File "/root/miniconda3/envs/zero/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1055, in _zero_init_param
    dist.broadcast(param.data, 0, self.get_dp_process_group())
  File "/root/miniconda3/envs/zero/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 117, in log_wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/zero/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 224, in broadcast
    return cdb.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
  File "/root/miniconda3/envs/zero/lib/python3.10/site-packages/deepspeed/comm/torch.py", line 206, in broadcast
    return torch.distributed.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
  File "/root/miniconda3/envs/zero/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 83, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/zero/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2417, in broadcast
    work = default_pg.broadcast([tensor], opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/NCCLUtils.hpp:317, invalid usage (run with NCCL_DEBUG=WARN for details), NCCL version 2.21.5
```

**Comment by Amanda2024** [comment]
I have the same questions！！！

**Comment by Amanda2024** [comment]
also error when i set --vllm_sync_backend gloo \

**Comment by wenxueru** [comment]
similar issue but different error at:
```
(LLMRayActor pid=21921, ip=10.39.1.20) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::RayWorkerWrapper.execute_method() (pid=22065, ip=10.39.1.20, actor_id=35de9637a3079d4314630ed239000000, repr=<vllm.executor.ray_utils.RayWorkerWrapper object at 0x7fbcbbd00550>) [repeated 7x across cluster]
(LLMRayActor pid=21921, ip=10.39.1.20)   File "/cpfs/user/wenxueru/miniconda3/envs/rlfh/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 566, in execute_method [repeated 14x across cluster]
(LLMRayActor pid=21921, ip=10.39.1.20)     raise e [repeated 7x across cluster]
(LLMRayActor pid=21921, ip=10.39.1.20)     return run_method(target, method, args, kwargs) [repeated 7x across cluster]
(LLMRayActor pid=21921, ip=10.39.1.20)   File "/cpfs/user/wenxueru/miniconda3/envs/rlfh/lib/python3.10/site-packages/vllm/utils.py", line 2220, in run_method [repeated 7x across cluster]
(LLMRayActor pid=21921, ip=10.39.1.20)     return func(*args, **kwargs) [repeated 7x across cluster]
(LLMRayActor pid=21921, ip=10.39.1.20)   File "/cpfs/user/wenxueru/agi-rlfh/repos/OpenRLHF/openrlhf/trainer/ray/vllm_worker_wrap.py", line 23, in init_process_group [repeated 7x across cluster]
(LLMRayActor pid=21921, ip=10.39.1.20)     collective.init_collective_group(world_size=world_size, rank=rank, backend=backend, group_name=group_name) [repeated 7x across cluster]
(LLMRayActor pid=21921, ip=10.39.1.20)   File "/cpfs/user/wenxueru/miniconda3/envs/rlfh/lib/python3.10/site-packages/ray/util/collective/collective.py", line 136, in init_collective_group [repeated 7x across cluster]
(LLMRayActor pid=21921, ip=10.39.1.20)     _check_backend_availability(backend) [repeated 7x across cluster]
(LLMRayActor pid=21921, ip=10.39.1.20)   File "/cpfs/user/wenxueru/miniconda3/envs/rlfh/lib/python3.10/site-packages/ray/util/collective/collective.py", line 731, in _check_backend_availability [repeated 7x across cluster]
(LLMRayActor pid=21921, ip=10.39.1.20)     raise RuntimeError("NCCL is not available.") [repeated 7x across cluster]
(LLMRayActor pid=21921, ip=10.39.1.20) RuntimeError: NCCL is not available. [repeated 7x across cluster]
```

**Comment by sastpg** [comment]
Hi, I came across the same problem when using ray==2.12.0, deepspeed==0.15.0.
But when I upgraded them, the problem solved:
`pip install deepspeed==0.16.3`
`pip install ray[default]==2.42.0`

**Comment by ywb2018** [comment]
> Hi, I came across the same problem when using ray==2.12.0, deepspeed==0.15.0. But when I upgraded them, the problem solved: `pip install deepspeed==0.16.3` `pip install ray[default]==2.42.0`

thanks a lot, solve my problem @sastpg
