### ISSUE TITLE
两个节点运行，卡住一直到超时然后包错，如何解决

### ISSUE THREAD

**Issue by pizts** [OpenRLHF/OpenRLHF#795]
Capturing CUDA graph shapes:   0%|          | 0/35 [00:00<?, ?it/s] [repeated 3x across cluster]
(LLMRayActor pid=15863) 
Capturing CUDA graph shapes:  23%|██▎       | 8/35 [00:05<00:18,  1.47it/s] [repeated 28x across cluster]
(LLMRayActor pid=15862) 
Capturing CUDA graph shapes:  49%|████▊     | 17/35 [00:10<00:09,  1.84it/s] [repeated 36x across cluster]
(LLMRayActor pid=15864) 
Capturing CUDA graph shapes:  74%|███████▍  | 26/35 [00:15<00:05,  1.80it/s] [repeated 39x across cluster]
(LLMRayActor pid=15862) 
Capturing CUDA graph shapes:  91%|█████████▏| 32/35 [00:18<00:01,  1.91it/s]
(LLMRayActor pid=15862) 
Capturing CUDA graph shapes: 100%|██████████| 35/35 [00:20<00:00,  1.32it/s]
Capturing CUDA graph shapes: 100%|██████████| 35/35 [00:20<00:00,  1.69it/s]
(LLMRayActor pid=15864) 
Capturing CUDA graph shapes:  89%|████████▊ | 31/35 [00:18<00:02,  1.83it/s] [repeated 20x across cluster]
(LLMRayActor pid=15862) INFO 02-26 10:42:34 model_runner.py:1562] Graph capturing finished in 21 secs, took 0.09 GiB
(LLMRayActor pid=15862) INFO 02-26 10:42:34 llm_engine.py:431] init engine (profile, create kv cache, warmup model) took 31.04 seconds
(LLMRayActor pid=15865) INFO 02-26 10:42:13 model_runner.py:1434] Capturing cudagraphs for decoding. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI. If out-of-memory error occurs during cudagraph capture, consider decreasing `gpu_memory_utilization` or switching to eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage. [repeated 3x across cluster]
(ActorModelRayActor pid=620, ip=22.0.135.20) 
(ActorModelRayActor pid=620, ip=22.0.135.20) [dlc1dr998nbmktm1-worker-0][620:1877][0][state_monitor.cc:243] NCCL WARN StateMonitor:ee43a6d68272cd1a:Rank2 : no pending work(s) completed over 60.00 seconds, channel 0, enqueued 2320, completed 2319
(ActorModelRayActor pid=620, ip=22.0.135.20) 
(ActorModelRayActor pid=620, ip=22.0.135.20) [dlc1dr998nbmktm1-worker-0][620:1887][0][state_monitor.cc:103] NCCL WARN StateMonitor:ee43a6d68272cd1a:Rank2 : trigger debugging dump
(ActorModelRayActor pid=620, ip=22.0.135.20) [dlc1dr998nbmktm1-worker-0][620:1887][0][comm_dumper.cc:439] NCCL INFO pccl comm:0x55cb32292980 dump start.
(ActorModelRayActor pid=620, ip=22.0.135.20) [dlc1dr998nbmktm1-worker-0][620:1887][0][comm_dumper.cc:39] NCCL INFO use default comm dump name pccl_comm_dump
(ActorModelRayActor pid=620, ip=22.0.135.20) [dlc1dr998nbmktm1-worker-0][620:1887][0][comm_dumper.cc:200] NCCL INFO dump comm rough to file:/root/.pccl/comm_dump/pccl_comm_dump_comm-ee43a6d68272cd1a_nranks-8_rank-2_dlc1dr998nbmktm1-worker-0_pid-620_20250226-104316.txt
(LLMRayActor pid=15864) INFO 02-26 10:42:34 model_runner.py:1562] Graph capturing finished in 22 secs, took 0.09 GiB [repeated 3x across cluster]
(LLMRayActor pid=15864) INFO 02-26 10:42:34 llm_engine.py:431] init engine (profile, create kv cache, warmup model) took 31.68 seconds [repeated 3x across cluster]
(ActorModelRayActor pid=620, ip=22.0.135.20) [dlc1dr998nbmktm1-worker-0][620:1887][0][comm_dumper.cc:475] NCCL INFO pccl comm:0x55cb32292980 dump finished.
(ActorModelRayActor pid=620, ip=22.0.135.20) [dlc1dr998nbmktm1-worker-0][620:1887][0][proxy.cc:123] NCCL INFO comm ee43a6d68272cd1a, rank 2, empty proxy state
Traceback (most recent call last):
  File "/tmp/ray/session_2025-02-26_10-39-19_211862_2/runtime_resources/working_dir_files/_ray_pkg_e9888018ffcc262c/openrlhf/cli/train_ppo_ray.py", line 431, in <module>
    train(args)
  File "/tmp/ray/session_2025-02-26_10-39-19_211862_2/runtime_resources/working_dir_files/_ray_pkg_e9888018ffcc262c/openrlhf/cli/train_ppo_ray.py", line 175, in train
    ray.get(refs)
  File "/usr/local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(DistStoreError): ray::ActorModelRayActor.fit() (pid=432, ip=22.0.135.20, actor_id=475c743bd27a88b4d934992402000000, repr=<openrlhf.trainer.ray.ppo_actor.ActorModelRayActor object at 0x7edbbae51120>)
  File "/tmp/ray/session_2025-02-26_10-39-19_211862_2/runtime_resources/working_dir_files/_ray_pkg_e9888018ffcc262c/openrlhf/trainer/ray/ppo_actor.py", line 439, in fit
    trainer = ActorPPOTrainer(
  File "/tmp/ray/session_2025-02-26_10-39-19_211862_2/runtime_resources/working_dir_files/_ray_pkg_e9888018ffcc262c/openrlhf/trainer/ray/ppo_actor.py", line 110, in __init__
    self._model_update_group = init_process_group(
  File "/tmp/ray/session_2025-02-26_10-39-19_211862_2/runtime_resources/working_dir_files/_ray_pkg_e9888018ffcc262c/openrlhf/utils/distributed_util.py", line 48, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/usr/local/lib/python3.10/site-packages/torch/distributed/rendezvous.py", line 221, in _tcp_rendezvous_handler
    store = _create_c10d_store(
  File "/usr/local/lib/python3.10/site-packages/torch/distributed/rendezvous.py", line 189, in _create_c10d_store
    return TCPStore(
torch.distributed.DistStoreError: Timed out after 1801 seconds waiting for clients. 1/5 clients joined.

**Comment by Rr-shan** [comment]
我也遇到了类似的问题，蹲一个回复

**Comment by Roysky** [comment]
一样的问题，qwen32B，配置信息如下
` --ref_num_nodes 1 \
    --ref_num_gpus_per_node 8 \
    --reward_num_nodes 1 \
    --reward_num_gpus_per_node 8 \
    --critic_num_nodes 1 \
    --critic_num_gpus_per_node 8 \
    --actor_num_nodes 1 \
    --actor_num_gpus_per_node 8 \`

**Comment by 2proveit** [comment]
应该是资源不够的问题，ray会先为vllm engines申请资源，然后再为actor，ref，critic，reward申请，
确保你使用了`--colocate_actor_ref`参数保证actor和ref在同样的卡上，不然你的设置`--ref_num_nodes 1  --ref_num_gpus_per_node 8  --reward_num_nodes 1  --reward_num_gpus_per_node 8`会分别占8张卡

**Comment by pizts** [comment]
> 应该是资源不够的问题，ray会先为vllm engines申请资源，然后再为actor，ref，critic，reward申请， 确保你使用了`--colocate_actor_ref`参数保证actor和ref在同样的卡上，不然你的设置`--ref_num_nodes 1 --ref_num_gpus_per_node 8 --reward_num_nodes 1 --reward_num_gpus_per_node 8`会分别占8张卡

好像不能解决，设置了--coloate_actor_ref会出现以下包错信息：
pid=17625) /usr/local/lib/python3.10/site-packages/deepspeed/runtime/zero/linear.py:49: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead. [repeated 7x across cluster]
(pid=17625)   def forward(ctx, input, weight, bias=None): [repeated 7x across cluster]
(pid=17625) /usr/local/lib/python3.10/site-packages/deepspeed/runtime/zero/linear.py:67: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead. [repeated 7x across cluster]
(pid=17625)   def backward(ctx, grad_output): [repeated 7x across cluster]
(ActorModelRayActor pid=16712) You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`. [repeated 3x across cluster]
(LLMRayActor pid=16099) INFO 02-27 14:11:11 cuda.py:230] Using Flash Attention backend. [repeated 3x across cluster]
(ActorModelRayActor pid=16712) [dlc1f0bnd3uip696-master-0][16712:16712][0][socket.h:481] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth [repeated 3x across cluster]
(ActorModelRayActor pid=16712) [dlc1f0bnd3uip696-master-0][16712:16712][0][bootstrap.cc:54] NCCL INFO Bootstrap : Using eth0:22.0.133.85<0> [repeated 3x across cluster]
(ActorModelRayActor pid=16712) [dlc1f0bnd3uip696-master-0][16712:16712][0][net_wrapper.cc:207] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v6 symbol. [repeated 3x across cluster]
(ActorModelRayActor pid=16712) [dlc1f0bnd3uip696-master-0][16712:16712][0][net_wrapper.cc:212] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin symbol (v4 or v5). [repeated 3x across cluster]
(ActorModelRayActor pid=16712) dlc1f0bnd3uip696-master-0 accl-lite version: v1.1.149.gd6267d6 [repeated 3x across cluster]
(ActorModelRayActor pid=16712) [dlc1f0bnd3uip696-master-0][16712:16712][0][pfFindInterfaces:352] NCCL INFO NET/accl-lite NCCL_SOCKET_IFNAME set by environment to eth [repeated 3x across cluster]
(ActorModelRayActor pid=16712) [dlc1f0bnd3uip696-master-0][16712:16712][0][pfFindInterfaces:354] NCCL INFO NET/accl-lite NCCL_SOCKET_IFNAME set to eth [repeated 3x across cluster]
(ActorModelRayActor pid=16712) [dlc1f0bnd3uip696-master-0][16712:16712][0][pfInit:1105] NCCL INFO NET/accl-lite unicm bind 22.0.133.85 [repeated 3x across cluster]
(ActorModelRayActor pid=16712) [dlc1f0bnd3uip696-master-0][16712:16712][0][get_pf_send_flag:770] NCCL INFO NET/accl-lite NCCL_PF_SEND_FLAG_RR set to 1 [repeated 3x across cluster]
(ActorModelRayActor pid=16712) [dlc1f0bnd3uip696-master-0][16712:16712][0][get_pf_cqe_order:850] NCCL INFO NET/accl-lite NCCL_PF_CQE_ORDER set to 1 [repeated 3x across cluster]
(ActorModelRayActor pid=16712) [dlc1f0bnd3uip696-master-0][16712:16712][0][pfInit:1145] NCCL INFO NET/accl-lite NCCL_IB_HCA set to  [repeated 3x across cluster]
(LLMRayActor pid=16099) INFO 02-27 14:11:12 model_runner.py:1110] Starting to load model /mnt/data/Models/Qwen2.5-14B-Instruct... [repeated 3x across cluster]
(ActorModelRayActor pid=16712) [dlc1f0bnd3uip696-master-0][16712:16712][0][pfInit:1354] NCCL INFO NET/accl-lite Init 4 SOE devices: [repeated 3x across cluster]
(ActorModelRayActor pid=16712) [dlc1f0bnd3uip696-master-0][16712:16712][0][pfInit:1361] NCCL INFO NET/accl-lite +---+----------------+ [repeated 15x across cluster]
(ActorModelRayActor pid=16712) [dlc1f0bnd3uip696-master-0][16712:16712][0][pfInit:1360] NCCL INFO NET/accl-lite | 3 | vsolar_3       | [repeated 12x across cluster]
(ActorModelRayActor pid=16712) [dlc1f0bnd3uip696-master-0][16712:16712][0][init.cc:300] NCCL INFO Using network accl-lite [repeated 3x across cluster]
(ActorModelRayActor pid=16712) [dlc1f0bnd3uip696-master-0][16712:17898][0][init.cc:1808] NCCL INFO ncclCommInitRank comm 0x556dfdf43810 rank 1 nranks 4 hggcDev 0 hgmlDev 0 busId 10 commHash 6d3621d612ab823d - Init START [repeated 3x across cluster]
(ActorModelRayActor pid=16712) [dlc1f0bnd3uip696-master-0][16712:17898][0][agent.cc:199] NCCL INFO [C4A] initialize: mode=1, path-opt=0, upload-stats=1, upload-period=2, disable_path=0, modify_path=0, path_status=0, upload-log=0, conn-retry-times=10, allocate_path_timeout=3, get_path_stats_period=60 [repeated 3x across cluster]
(ActorModelRayActor pid=16101) [dlc1f0bnd3uip696-master-0][16101:17880][0][agent.cc:381] NCCL INFO [C4A] failed to connect c4d: errno:111(Connection refused), retry time:3 [repeated 12x across cluster]
(pid=17635) INFO 02-27 14:11:18 __init__.py:190] Automatically detected platform cuda.
(pid=17632) [2025-02-27 14:11:16,020] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect) [repeated 3x across cluster]
(pid=17632)  [WARNING]  async_io requires the dev libaio .so object and headers but these were not found. [repeated 3x across cluster]
(pid=17632)  [WARNING]  async_io: please install the libaio-dev package with apt [repeated 3x across cluster]
(pid=17632)  [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found. [repeated 3x across cluster]
(pid=17632)  [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH [repeated 3x across cluster]
(LLMRayActor pid=16100) 
Loading safetensors checkpoint shards:   0% Completed | 0/8 [00:00<?, ?it/s] [repeated 3x across cluster]
(ActorModelRayActor pid=16712) set_mempolicy: Invalid argument [repeated 12x across cluster]
(ReferenceModelRayActor pid=16715) [dlc1f0bnd3uip696-master-0][16715:18251][0][bootstrap.cc:131] NCCL INFO bootstrapRoot Listening on socket 22.0.133.85<54329>
(ReferenceModelRayActor pid=16715) PCCL version 1.4.0-7-accl-p, COMMIT_ID 2625422, BUILD_TIME 2024-12-31 11:29:20
(pid=17635)  [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.5 [repeated 3x across cluster]
(pid=17635)  [WARNING]  using untested triton version (3.1.0), only 1.0.0 is known to be compatible [repeated 3x across cluster]
(ReferenceModelRayActor pid=17625) [2025-02-27 14:11:18,761] [INFO] [comm.py:637:init_distributed] cdb=None [repeated 3x across cluster]
(LLMRayActor pid=16097) 
Loading safetensors checkpoint shards:  12% Completed | 1/8 [00:10<01:12, 10.41s/it]
(pid=17635) /usr/local/lib/python3.10/site-packages/deepspeed/runtime/zero/linear.py:49: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead. [repeated 2x across cluster]
(pid=17635)   def forward(ctx, input, weight, bias=None): [repeated 2x across cluster]
(pid=17635) /usr/local/lib/python3.10/site-packages/deepspeed/runtime/zero/linear.py:67: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead. [repeated 2x across cluster]
(pid=17635)   def backward(ctx, grad_output): [repeated 2x across cluster]
(ReferenceModelRayActor pid=17632) You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`. [repeated 4x across cluster]
(ReferenceModelRayActor pid=17632) [dlc1f0bnd3uip696-master-0][17632:17632][0][socket.h:481] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth [repeated 4x across cluster]
(ReferenceModelRayActor pid=17632) [dlc1f0bnd3uip696-master-0][17632:17632][0][bootstrap.cc:54] NCCL INFO Bootstrap : Using eth0:22.0.133.85<0> [repeated 4x across cluster]
(ReferenceModelRayActor pid=17632) [dlc1f0bnd3uip696-master-0][17632:17632][0][net_wrapper.cc:207] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin_v6 symbol. [repeated 4x across cluster]
(ReferenceModelRayActor pid=17632) [dlc1f0bnd3uip696-master-0][17632:17632][0][net_wrapper.cc:212] NCCL INFO NET/Plugin: Failed to find ncclCollNetPlugin symbol (v4 or v5). [repeated 4x across cluster]
(ReferenceModelRayActor pid=17632) dlc1f0bnd3uip696-master-0 accl-lite version: v1.1.149.gd6267d6 [repeated 4x across cluster]
(ReferenceModelRayActor pid=17632) [dlc1f0bnd3uip696-master-0][17632:17632][0][pfFindInterfaces:352] NCCL INFO NET/accl-lite NCCL_SOCKET_IFNAME set by environment to eth [repeated 4x across cluster]
(ReferenceModelRayActor pid=17632) [dlc1f0bnd3uip696-master-0][17632:17632][0][pfFindInterfaces:354] NCCL INFO NET/accl-lite NCCL_SOCKET_IFNAME set to eth [repeated 4x across cluster]
(ReferenceModelRayActor pid=17632) [dlc1f0bnd3uip696-master-0][17632:17632][0][pfInit:1105] NCCL INFO NET/accl-lite unicm bind 22.0.133.85 [repeated 4x across cluster]
(ReferenceModelRayActor pid=17632) [dlc1f0bnd3uip696-master-0][17632:17632][0][get_pf_send_flag:770] NCCL INFO NET/accl-lite NCCL_PF_SEND_FLAG_RR set to 1 [repeated 4x across cluster]
(ReferenceModelRayActor pid=17632) [dlc1f0bnd3uip696-master-0][17632:17632][0][get_pf_cqe_order:850] NCCL INFO NET/accl-lite NCCL_PF_CQE_ORDER set to 1 [repeated 4x across cluster]
(ReferenceModelRayActor pid=17632) [dlc1f0bnd3uip696-master-0][17632:17632][0][pfInit:1145] NCCL INFO NET/accl-lite NCCL_IB_HCA set to  [repeated 4x across cluster]
(ReferenceModelRayActor pid=17632) [dlc1f0bnd3uip696-master-0][17632:17632][0][pfInit:1354] NCCL INFO NET/accl-lite Init 4 SOE devices: [repeated 4x across cluster]
(ReferenceModelRayActor pid=17632) [dlc1f0bnd3uip696-master-0][17632:17632][0][pfInit:1361] NCCL INFO NET/accl-lite +---+----------------+ [repeated 20x across cluster]
(ReferenceModelRayActor pid=17632) [dlc1f0bnd3uip696-master-0][17632:17632][0][pfInit:1360] NCCL INFO NET/accl-lite | 3 | vsolar_3       | [repeated 16x across cluster]
(ReferenceModelRayActor pid=17632) [dlc1f0bnd3uip696-master-0][17632:17632][0][init.cc:300] NCCL INFO Using network accl-lite [repeated 4x across cluster]
(ReferenceModelRayActor pid=17632) [dlc1f0bnd3uip696-master-0][17632:18271][0][init.cc:1808] NCCL INFO ncclCommInitRank comm 0x56358f36b0f0 rank 2 nranks 4 hggcDev 0 hgmlDev 1 busId 20 commHash 6ca4a17260ea044c - Init START [repeated 4x across cluster]
(ReferenceModelRayActor pid=17632) [dlc1f0bnd3uip696-master-0][17632:18271][0][agent.cc:199] NCCL INFO [C4A] initialize: mode=1, path-opt=0, upload-stats=1, upload-period=2, disable_path=0, modify_path=0, path_status=0, upload-log=0, conn-retry-times=10, allocate_path_timeout=3, get_path_stats_period=60 [repeated 4x across cluster]
(ActorModelRayActor pid=16101) [dlc1f0bnd3uip696-master-0][16101:17880][0][agent.cc:381] NCCL INFO [C4A] failed to connect c4d: errno:111(Connection refused), retry time:6 [repeated 21x across cluster]
(pid=17625) INFO 02-27 14:11:18 __init__.py:190] Automatically detected platform cuda. [repeated 2x across cluster]
(ReferenceModelRayActor pid=16715) [dlc1f0bnd3uip696-master-0][16715:18252][0][agent.cc:381] NCCL INFO [C4A] failed to connect c4d: errno:111(Connection refused), retry time:5 [repeated 20x across cluster]
(ActorModelRayActor pid=16101) [dlc1f0bnd3uip696-master-0][16101:17880][0][agent.cc:390] NCCL INFO [C4A] WARN failed to connect c4d after 10 retrys
(ActorModelRayActor pid=16101) [dlc1f0bnd3uip696-master-0][16101:17880][0][c4_net.cc:334] NCCL INFO WARN Stats : Failed to init C4 agent, disable C4 stats
(ActorModelRayActor pid=16101) [dlc1f0bnd3uip696-master-0][16101:17880][0][init.cc:134] NCCL INFO gTaskid = 6d3621d612ab823d.
(ActorModelRayActor pid=16101) 
(ActorModelRayActor pid=16101) [dlc1f0bnd3uip696-master-0][16101:17880][0][init.cc:1183] NCCL ERROR Duplicate PPU detected : rank 0 and rank 1 both on HGGC device 10
(ActorModelRayActor pid=16101) 
(ActorModelRayActor pid=16101) [dlc1f0bnd3uip696-master-0][16101:17880][0][init.cc:1815] NCCL WARN init.cc:1815 -> 5
(ActorModelRayActor pid=16101) [dlc1f0bnd3uip696-master-0][16101:17880][0][group.cc:74] NCCL INFO /ACCL-P/src/group.cc:74 -> 5 [Async thread]
(ActorModelRayActor pid=16101) 
(ActorModelRayActor pid=16101) [dlc1f0bnd3uip696-master-0][16101:16101][0][group.cc:585] NCCL WARN group.cc:585 -> 3
(ActorModelRayActor pid=16101) 
(ActorModelRayActor pid=16101) [dlc1f0bnd3uip696-master-0][16101:16101][0][init.cc:2103] NCCL WARN init.cc:2103 -> 3
Traceback (most recent call last):
  File "/tmp/ray/session_2025-02-27_14-10-32_704945_3/runtime_resources/working_dir_files/_ray_pkg_1431537dea4b986e/openrlhf/cli/train_ppo_ray.py", line 437, in <module>
    train(args)
  File "/tmp/ray/session_2025-02-27_14-10-32_704945_3/runtime_resources/working_dir_files/_ray_pkg_1431537dea4b986e/openrlhf/cli/train_ppo_ray.py", line 166, in train
    ray.get(refs)
  File "/usr/local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(DistBackendError): ray::ActorModelRayActor.init_model_from_pretrained() (pid=16712, ip=0.0.0.0, actor_id=9fa9830cc79ffdd6aacac60902000000, repr=<openrlhf.trainer.ray.ppo_actor.ActorModelRayActor object at 0x7f70cc344d90>)
  File "/tmp/ray/session_2025-02-27_14-10-32_704945_3/runtime_resources/working_dir_files/_ray_pkg_1431537dea4b986e/openrlhf/trainer/ray/ppo_actor.py", line 282, in init_model_from_pretrained
    actor = Actor(
  File "/tmp/ray/session_2025-02-27_14-10-32_704945_3/runtime_resources/working_dir_files/_ray_pkg_1431537dea4b986e/openrlhf/models/actor.py", line 73, in __init__
    self.model = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4097, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/usr/local/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 506, in wrapper
    f(module, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1083, in __init__
    self.model = Qwen2Model(config)
  File "/usr/local/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 506, in wrapper
    f(module, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 789, in __init__
    self.embed_tokens = nn.Embedding(config.vocab_size, config.hidden_size, self.padding_idx)
  File "/usr/local/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 516, in wrapper
    self._post_init_method(module)
  File "/usr/local/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1081, in _post_init_method
    self._zero_init_param(param)
  File "/usr/local/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1036, in _zero_init_param
    dist.broadcast(param.data, 0, self.get_dp_process_group())
  File "/usr/local/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 117, in log_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/deepspeed/comm/comm.py", line 224, in broadcast
    return cdb.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
  File "/usr/local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 632, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/deepspeed/comm/torch.py", line 199, in broadcast
    return torch.distributed.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
  File "/usr/local/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 83, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2417, in broadcast
    work = default_pg.broadcast([tensor], opts)
torch.distributed.DistBackendError: NCCL error in: /job_2197767/source/pytorch/torch/csrc/distributed/c10d/NCCLUtils.hpp:317, internal error, NCCL version 2.19.3
ncclInternalError: Internal check failed.
Last error:
init.cc:2103 -> 3


不设置--coloate_actor_ref的话，还是会出现tcp timeout的那个错误。其他参数是这样的
ray job submit --address="http://127.0.0.1:8265" \
   --runtime-env-json='{"working_dir": "/OpenRLHF"}' \
   -- python openrlhf/cli/train_ppo_ray.py \
   --ref_num_nodes 1 \
   --ref_num_gpus_per_node 4 \
   --actor_num_nodes 1 \
   --actor_num_gpus_per_node 4 \
   --vllm_num_engines 8 \
   --vllm_tensor_parallel_size 1 \
   --enable_prefix_caching \
   --pretrain /path/to/model_load \
   --remote_rm_url examples/scripts/reward_func.py \
   --save_path /path/to/model_save \
   --micro_train_batch_size 4 \
   --train_batch_size 32 \
   --micro_rollout_batch_size 32 \
   --rollout_batch_size 512 \
   --n_samples_per_prompt 8 \
   --max_epochs 1 \
   --prompt_max_len 8192 \
   --max_samples 100000 \
   --generate_max_len 2048 \
   --advantage_estimator reinforce_baseline \
   --zero_stage 3 \
   --bf16 \
   --actor_learning_rate 8e-6 \
   --init_kl_coef 1e-4 \
   --prompt_data /path/to/data.json \
   --input_key input_key \
   --label_key label_key \
   --normalize_reward \
   --gradient_checkpointing \
   --packing_samples \
   --flash_attn \
   --adam_offload \
   --use_kl_loss \
   --use_kl_estimator_k3 \
   --save_steps 10 \
   --ckpt_path /path/to/model_save \
   --use_tensorboard /path/to/model_save

**Comment by 2proveit** [comment]
看一下你的deepspeed版本

**Comment by pizts** [comment]
> 看一下你的deepspeed版本

deepspeed 0.14.4
vllm 0.7.2

**Comment by 2proveit** [comment]
官方不是使用0.16.3吗？要不你按照官方配置更新一下试试？
[https://github.com/OpenRLHF/OpenRLHF/blob/273422305ea17362319f5569c6f9ef5a16b49cb0/requirements.txt#L4](https://github.com/OpenRLHF/OpenRLHF/blob/273422305ea17362319f5569c6f9ef5a16b49cb0/requirements.txt#L4)

**Comment by pizts** [comment]
> 官方不是使用0.16.3吗？要不你按照官方配置更新一下试试？
> 
> [OpenRLHF/requirements.txt](https://github.com/OpenRLHF/OpenRLHF/blob/273422305ea17362319f5569c6f9ef5a16b49cb0/requirements.txt#L4)
> 
> Line 4 in [2734223](/OpenRLHF/OpenRLHF/commit/273422305ea17362319f5569c6f9ef5a16b49cb0)
> 
>  deepspeed==0.16.3

试了下，还是不行，还是报类似的错误。

**Comment by yikedouer** [comment]
我遇到类似问题，是因为master和worker启动地址没写好，可以检查下能否通信

**Comment by kuhne12** [comment]
same issue

**Comment by pizts** [comment]
> 我遇到类似问题，是因为master和worker启动地址没写好，可以检查下能否通信

果然是这个原因，master和worker启动地址没写好。改了之后就解决了。

**Comment by limitedfxw** [comment]
> > 我遇到类似问题，是因为master和worker启动地址没写好，可以检查下能否通信
> 
> 果然是这个原因，master和worker启动地址没写好。改了之后就解决了。
怎么设置的啊

**Comment by chuangzhidan** [comment]
> 我遇到类似问题，是因为master和worker启动地址没写好，可以检查下能否通信

怎么设置呢

**Comment by Siri-2001** [comment]
> > 我遇到类似问题，是因为master和worker启动地址没写好，可以检查下能否通信
> 
> 果然是这个原因，master和worker启动地址没写好。改了之后就解决了。

请问如何解决呢

**Comment by pizts** [comment]
master节点: ray start --head --port 6379 --num-gpus 8 #不设置--node-ip-address(尝试过可以启动)，或者设置--node-ip-address为127.0.0.0(没试过，可以试试)
worker节点: ray start --address=${MASTER_ADDR}:6379 --num-gpus 8 --block
