### ISSUE TITLE
OutOfMemoryError: Task was killed due to the node running low on memory.

### ISSUE THREAD

**Issue by yaxundai** [OpenRLHF/OpenRLHF#911]
8*A800 CPU memory is 250GB, train 7B model for REINFORCE++.

Start the script:
```
N_SAMPLES=16
EPISODE=10000
WARMUP=0.0
TBS=256
RBS=64
KL=0.0
LR=2e-6
MAX_LENGTH=4096
PORT=1278
TEMP=1.0
ray job submit --address="http://127.0.0.1:8865" \
   -- python3 -m openrlhf.cli.train_ppo_ray \
   --ref_num_nodes 1 \
   --ref_num_gpus_per_node 4 \
   --actor_num_nodes 1 \
   --actor_num_gpus_per_node 4 \
   --vllm_num_engines 2 \
   --vllm_tensor_parallel_size 2 \
   --colocate_actor_ref \
   --pretrain ${TOKENIZER_PATH} \
   --remote_rm_url http://localhost:${PORT}/get_reward \
   --save_path $SAVE_MODEL_NAME \
   --ckpt_path $SAVE_MODEL_NAME \
   --micro_train_batch_size 1 \
   --train_batch_size ${TBS} \
   --micro_rollout_batch_size 1 \
   --rollout_batch_size ${RBS} \
   --advantage_estimator reinforce_baseline \
   --max_samples 100000 \
   --max_epochs 1 \
   --num_episodes ${EPISODE} \
   --lr_warmup_ratio ${WARMUP} \
   --n_samples_per_prompt $N_SAMPLES \
   --prompt_max_len 2560 \
   --generate_max_len $MAX_LENGTH \
   --zero_stage 2 \
   --bf16 \
   --load_checkpoint \
   --actor_learning_rate $LR \
   --critic_learning_rate 9e-6 \
   --init_kl_coef $KL \
   --prompt_data $DATA_PATH \
   --input_key question \
   --flash_attn \
   --gradient_checkpointing \
   --save_steps 20 \
   --vllm_sync_backend nccl \
   --max_ckpt_num 3 \
   --temperature $TEMP \
   --overlap_comm \
   --packing_samples \
   --use_wandb ${wandb_token} \
   --wandb_group ${wandb_entity} \
   --wandb_project ${wandb_project} \
   --wandb_run_name $SAVE_MODEL_NAME \
   # --apply_chat_template \
```

#### Report an error message
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/nfsdata3/daiyaxun/project/R1-Searcher/OpenRLHF-RAG/openrlhf/cli/train_ppo_ray.py", line 414, in <module>
    train(args)
  File "/nfsdata3/daiyaxun/project/R1-Searcher/OpenRLHF-RAG/openrlhf/cli/train_ppo_ray.py", line 177, in train
    ray.get(refs)
  File "/nfsdata3/daiyaxun/env/R1_Searcher_v2/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/nfsdata3/daiyaxun/env/R1_Searcher_v2/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/nfsdata3/daiyaxun/env/R1_Searcher_v2/lib/python3.11/site-packages/ray/_private/worker.py", line 2623, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfsdata3/daiyaxun/env/R1_Searcher_v2/lib/python3.11/site-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(OutOfMemoryError): [36mray::ActorModelRayActor.fit()[39m (pid=8249, ip=0.0.0.0, actor_id=dd096be646751914e583a41404000000, repr=<openrlhf.trainer.ray.ppo_actor.ActorModelRayActor object at 0x7f9cc8e0a9d0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfsdata3/daiyaxun/project/R1-Searcher/OpenRLHF-RAG/openrlhf/trainer/ray/ppo_actor.py", line 397, in fit
    trainer.fit(
  File "/nfsdata3/daiyaxun/project/R1-Searcher/OpenRLHF-RAG/openrlhf/trainer/ppo_trainer.py", line 257, in fit
    status = self.ppo_train(steps)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/nfsdata3/daiyaxun/project/R1-Searcher/OpenRLHF-RAG/openrlhf/trainer/ray/ppo_actor.py", line 124, in ppo_train
    self._broadcast_to_vllm()
  File "/nfsdata3/daiyaxun/project/R1-Searcher/OpenRLHF-RAG/openrlhf/trainer/ray/ppo_actor.py", line 158, in _broadcast_to_vllm
    ray.get(refs)
           ^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ray.exceptions.RayTaskError(OutOfMemoryError): [36mray::LLMRayActor.update_weight()[39m (pid=8806, ip=0.0.0.0, actor_id=70a0e065e91f114143c9cc8804000000, repr=<openrlhf.trainer.ray.vllm_engine.LLMRayActor object at 0x7fa2bfefeb90>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfsdata3/daiyaxun/project/R1-Searcher/OpenRLHF-RAG/openrlhf/trainer/ray/vllm_engine.py", line 75, in update_weight
    return self.llm.llm_engine.model_executor._run_workers("update_weight", name, dtype, shape, empty_cache)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nfsdata3/daiyaxun/env/R1_Searcher_v2/lib/python3.11/site-packages/vllm/executor/ray_gpu_executor.py", line 404, in _run_workers
    ray_worker_outputs = ray.get(ray_worker_outputs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ray.exceptions.OutOfMemoryError: Task was killed due to the node running low on memory.
Memory on the node (IP: 0.0.0.0, ID: a9363377acd59b9250ec20f0bad51fcde35a25e5efe0079d061df289) where the task (actor ID: b68c96efed89e922d7fc07f504000000, name=RayWorkerWrapper.__init__, pid=9529, memory used=8.30GB) was running was 239.02GB / 251.56GB (0.950143), which exceeds the memory usage threshold of 0.95. Ray killed this worker (ID: dea10b4a716114835d8d6df2758c3be01126100f566235e910027141) because it was the most recently scheduled task; to see more information about memory usage on this node, use `ray logs raylet.out -ip 0.0.0.0`. To see the logs of the worker, use `ray logs worker-dea10b4a716114835d8d6df2758c3be01126100f566235e910027141*out -ip 0.0.0.0. Top 10 memory users:
PID	MEM(GB)	COMMAND
14	176.97	python train/nl2sql_reward.py --reward_pretrain /nfsdata3/daiyaxun/model/Qwen/Qwen2.5-Coder-7B-Instr...
8805	8.80	ray::LLMRayActor
8806	8.79	ray::LLMRayActor
9529	8.30	ray::RayWorkerWrapper
9528	8.30	ray::RayWorkerWrapper
8385	2.55	ray::ActorModelRayActor.fit
8384	2.36	ray::ActorModelRayActor.fit
8249	1.90	ray::ActorModelRayActor.fit
8383	1.66	ray::ActorModelRayActor.fit
8800	1.18	ray::ReferenceModelRayActor
Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. Set max_restarts and max_task_retries to enable retry when the task crashes due to OOM. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.
[36m(ActorModelRayActor pid=8249)[0m Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): [36mray::LLMRayActor.update_weight()[39m (pid=8805, ip=0.0.0.0, actor_id=21039d4a21c39ca5e8311f3804000000, repr=<openrlhf.trainer.ray.vllm_engine.LLMRayActor object at 0x7f1ae687df50>)
[36m(ActorModelRayActor pid=8249)[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(ActorModelRayActor pid=8249)[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(ActorModelRayActor pid=8249)[0m   File "/nfsdata3/daiyaxun/project/R1-Searcher/OpenRLHF-RAG/openrlhf/trainer/ray/vllm_engine.py", line 75, in update_weight
[36m(ActorModelRayActor pid=8249)[0m     return self.llm.llm_engine.model_executor._run_workers("update_weight", name, dtype, shape, empty_cache)
[36m(ActorModelRayActor pid=8249)[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(ActorModelRayActor pid=8249)[0m   File "/nfsdata3/daiyaxun/env/R1_Searcher_v2/lib/python3.11/site-packages/vllm/executor/ray_gpu_executor.py", line 404, in _run_workers
[36m(ActorModelRayActor pid=8249)[0m     ray_worker_outputs = ray.get(ray_worker_outputs)
[36m(ActorModelRayActor pid=8249)[0m                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(ActorModelRayActor pid=8249)[0m            ^^^^^^^^^^^^^^^^^^^
[36m(ActorModelRayActor pid=8249)[0m            ^^^^^^^^^^^^^^^^^^^^^
[36m(ActorModelRayActor pid=8249)[0m                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(ActorModelRayActor pid=8249)[0m ray.exceptions.OutOfMemoryError: Task was killed due to the node running low on memory.
[36m(ActorModelRayActor pid=8249)[0m Memory on the node (IP: 0.0.0.0, ID: a9363377acd59b9250ec20f0bad51fcde35a25e5efe0079d061df289) where the task (actor ID: aa91f5ecc54d86a55361889f04000000, name=RayWorkerWrapper.__init__, pid=9528, memory used=8.30GB) was running was 239.00GB / 251.56GB (0.950072), which exceeds the memory usage threshold of 0.95. Ray killed this worker (ID: be19e8ecfa0ede9a5887023561f7e9ef9fe21d7f9f772005bb77ed1a) because it was the most recently scheduled task; to see more information about memory usage on this node, use `ray logs raylet.out -ip 0.0.0.0`. To see the logs of the worker, use `ray logs worker-be19e8ecfa0ede9a5887023561f7e9ef9fe21d7f9f772005bb77ed1a*out -ip 0.0.0.0. Top 10 memory users:
[36m(ActorModelRayActor pid=8249)[0m PID	MEM(GB)	COMMAND
[36m(ActorModelRayActor pid=8249)[0m 14	185.38	python train/nl2sql_reward.py --reward_pretrain /nfsdata3/daiyaxun/model/Qwen/Qwen2.5-Coder-7B-Instr...
[36m(ActorModelRayActor pid=8249)[0m 8805	8.80	ray::LLMRayActor
[36m(ActorModelRayActor pid=8249)[0m 8806	8.79	ray::LLMRayActor
[36m(ActorModelRayActor pid=8249)[0m 9528	8.30	ray::RayWorkerWrapper
[36m(ActorModelRayActor pid=8249)[0m 8385	2.55	ray::ActorModelRayActor.fit
[36m(ActorModelRayActor pid=8249)[0m 8384	2.36	ray::ActorModelRayActor.fit
[36m(ActorModelRayActor pid=8249)[0m 8249	1.92	ray::ActorModelRayActor.fit
[36m(ActorModelRayActor pid=8249)[0m 8383	1.66	ray::ActorModelRayActor.fit
[36m(ActorModelRayActor pid=8249)[0m 8800	1.18	ray::ReferenceModelRayActor
[36m(ActorModelRayActor pid=8249)[0m 8798	1.17	ray::ReferenceModelRayActor
[36m(ActorModelRayActor pid=8249)[0m Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. Set max_restarts and max_task_retries to enable retry when the task crashes due to OOM. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.
[36m(ActorModelRayActor pid=8249)[0m 
Episode [1/10000]:   7%|▋         | 11/147 [3:34:08<44:07:37, 1168.07s/it, policy_loss=-0.115, actor_lr=2e-6, kl=0.106, reward=1.93, response_length=369, total_length=1.74e+3, retrieve_num=1.46, pure_response_length=339, return=-1.98e-9]
[36m(LLMRayActor pid=8805)[0m update weight: model.embed_tokens.weight, dtype: torch.bfloat16, shape: torch.Size([152064, 3584])
[36m(ActorModelRayActor pid=8249)[0m  0.0[32m [repeated 34x across cluster][0m
[36m(ActorModelRayActor pid=8249)[0m        device='cuda:0'),type:<class 'torch.Tensor'>
[36m(ActorModelRayActor pid=8249)[0m kl_coef: 0.0[32m [repeated 284x across cluster][0m
[36m(LLMRayActor pid=8806)[0m update weight: model.embed_tokens.weight, dtype: torch.bfloat16, shape: torch.Size([152064, 3584])
2025-03-24 14:49:45,286	ERR cli.py:68 -- [31m---------------------------------------[39m
2025-03-24 14:49:45,286	ERR cli.py:69 -- [31mJob 'raysubmit_h6pyehYCNXRbuirW' failed[39m
2025-03-24 14:49:45,286	ERR cli.py:70 -- [31m---------------------------------------[39m
2025-03-24 14:49:45,286	INFO cli.py:83 -- Status message: Job entrypoint command failed with exit code 1, last available logs (truncated to 20,000 chars):
[36m(ActorModelRayActor pid=8249)[0m 8800	1.18	ray::ReferenceModelRayActor
[36m(ActorModelRayActor pid=8249)[0m 8798	1.17	ray::ReferenceModelRayActor
[36m(ActorModelRayActor pid=8249)[0m Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. Set max_restarts and max_task_retries to enable retry when the task crashes due to OOM. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.
[36m(ActorModelRayActor pid=8249)[0m 
Episode [1/10000]:   7%|▋         | 11/147 [3:34:08<44:07:37, 1168.07s/it, policy_loss=-0.115, actor_lr=2e-6, kl=0.106, reward=1.93, response_length=369, total_length=1.74e+3, retrieve_num=1.46, pure_response_length=339, return=-1.98e-9]
[36m(LLMRayActor pid=8805)[0m update weight: model.embed_tokens.weight, dtype: torch.bfloat16, shape: torch.Size([152064, 3584])
[36m(ActorModelRayActor pid=8249)[0m  0.0[32m [repeated 34x across cluster][0m
[36m(ActorModelRayActor pid=8249)[0m        device='cuda:0'),type:<class 'torch.Tensor'>
[36m(ActorModelRayActor pid=8249)[0m kl_coef: 0.0[32m [repeated 284x across cluster][0m
[36m(LLMRayActor pid=8806)[0m update weight: model.embed_tokens.weight, dtype: torch.bfloat16, shape: torch.Size([152064, 3584])

```

##### Device usage

![Image](https://github.com/user-attachments/assets/4fdca1f0-7310-4914-981e-152cd1871511)

**Comment by hijkzzz** [comment]
用 zero3 + adam offload
或者 Hybrid engine + deepspeed sleep

**Comment by yaxundai** [comment]
> 用 zero3 + adam offload 或者 Hybrid engine + deepspeed sleep

Thank you, this worked
